### ISSUE TITLE
Cannot install elephas 3.4.2

### ISSUE THREAD

**Issue by blankdots** [danielenricocahall/elephas#17]
**Describe the bug**
Cannot install elephas, seems to happen with the latest version 3.4.2

The error is, when i try to upgrade (it is similar when I try a fresh install):
```
Requirement already satisfied: elephas in /usr/local/lib/python3.9/site-packages (3.1.0)
Collecting elephas
  Downloading elephas-3.4.2.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8kxk_o1d/elephas_a86f277830374d25acc15784076e2a61/setup.py", line 11, in <module>
          install_requires=[line.strip() for line in open('requirements.txt').readlines()],
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
```

**To Reproduce**
Steps to reproduce the behavior.
```
pip install --upgrade elephas
#or
pip install elephas
```

**Expected behavior**
Able to install elephas

**Desktop (please complete the following information):**
 - OS: CentOS 
 - Version 7
tried also on:
 - OS: Ubuntu
 - Version 20

Python version: `3.9`
pip version: `22.1.1`

**Additional context**

**Comment by danielenricocahall** [comment]
Good catch, thank you! That has been corrected, and along with some other changes for copying the documentation over to PyPI, has been bundled into 3.4.6. Please try again at earliest convenience!

**Comment by blankdots** [comment]
seems to work, closing as completed
