### ISSUE TITLE
Unable to run last step of `elephas/examples/ml_mlp_classification.py`

### ISSUE THREAD

**Issue by Yoseph-Zuskin** [danielenricocahall/elephas#4]
I get the following error when trying to run the [second last line of `elephas/examples/ml_mlp_classification.py`](https://github.com/danielenricocahall/elephas/blob/master/examples/ml_mlp_classification.py#L86):
```
TypeError: precision() missing 1 required positional argument: 'label'
```

**Comment by danielenricocahall** [comment]
Hello @Yoseph-Zuskin, yes it looks like the API changed plus the output format from the model during classification changed a few releases ago. I just made the update to fix the example and also illustrate how to use `MulticlassMetrics`. Thank you!
